<a href="https://colab.research.google.com/github/naoya1110/ai_robotics_lab_2022_hands_on/blob/main/Week03_Introduction_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NCKU-NITKC AI Robotics Lab - Week 03

In this AI Robotics Lab course, we will be using PyTorch for implementing deep neural networks. In this notebook we will learn basic functions of PyTorch. So let's get used to it.


*If you are not familier with basic Python programming, you may want to go through some other tutorials such as

https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb

## Torch.Tensor
First we need to import PyTorch.

In [1]:
import torch

PyTorch handles multi-dimensional array data with `torch.tensor` data type. To make a `torch.tensor` data, we can pass a Python `list` data to `torch.tensor()`.

In [2]:
a = [1, 2, 3]      # create list named "a"

print(a)           # show "a"
print(type(a))     # show data type of "a"

[1, 2, 3]
<class 'list'>


In [3]:
a = torch.tensor(a)     # convert list "a" to torch.tensor "a"

print(a)
print(type(a))

tensor([1, 2, 3])
<class 'torch.Tensor'>


Also, a `torch.tensor` data can be made from a `numpy.ndarray` data.

In [4]:
import numpy as np               # import Numpy package, "np" is abbreviation for numpy

b = np.array([0.4, 0.5, 0.6])    # create a np.ndarray named "b"
b = torch.tensor(b)              # convert np.ndarry "b" to torch.tensor "b"

print(b)
print(type(b))

tensor([0.4000, 0.5000, 0.6000], dtype=torch.float64)
<class 'torch.Tensor'>


It is also possible to convert a `torch.tensor` back to a `numpy.ndarray`.

In [5]:
c = b.numpy()        # convert torch.tensor data "b" to np.ndarray data "c"

print(c)
print(type(c))

[0.4 0.5 0.6]
<class 'numpy.ndarray'>


To know the shape of torch.tensor data, there are 2 different ways. One is `.shape` and the other is `.size()`. They return same result.

In [7]:
a = torch.tensor([1, 2, 3])
print(a.shape)

torch.Size([3])


In [8]:
print(a.size())

torch.Size([3])


## Simple Calculations

Let's do some simple arithmetic operations with a `torch.tensor` and a number.

In [9]:
a = torch.tensor([1, 2, 3])
print("a =", a)

print("a+1=", a+1)    # addition
print("a-2=", a-2)    # subtraction
print("a*3=", a*3)    # multiplication
print("a/4=", a/4)    # division

a = tensor([1, 2, 3])
a+1= tensor([2, 3, 4])
a-2= tensor([-1,  0,  1])
a*3= tensor([3, 6, 9])
a/4= tensor([0.2500, 0.5000, 0.7500])


Operations with two `torch.tensor`s.

In [10]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([0.4, 0.5, 0.6])

print("a =", a)
print("b =", b)

print("a+b=", a+b)
print("a-b=", a-b)
print("a*b=", a*b)
print("a/b=", a/b)

a = tensor([1, 2, 3])
b = tensor([0.4000, 0.5000, 0.6000])
a+b= tensor([1.4000, 2.5000, 3.6000])
a-b= tensor([0.6000, 1.5000, 2.4000])
a*b= tensor([0.4000, 1.0000, 1.8000])
a/b= tensor([2.5000, 4.0000, 5.0000])


## PyTorch and Numpy

Since PyTorch is based on Numpy, they have a lot of similarities. If you are already familier with Numpy, you might feel confortable with PyTorch as well. Let's see some examples.

**Zeros Array** - all zero array with given shape

In [11]:
np.zeros(3)    # 1D np.ndarray of 3 zeros

array([0., 0., 0.])

In [12]:
torch.zeros(3) # 1D torch.tensor of 3 zeros

tensor([0., 0., 0.])

In [13]:
torch.zeros((2, 3)) # 2D torch.tensor of 2x3 zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

**Ones Array** - all one array with given shape

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

**Random Number Array** - an array of rundom numbers between 0.0 and 1.0 with given shape

In [16]:
np.random.rand(3)

array([0.21820505, 0.78390608, 0.00824854])

In [17]:
torch.rand(3)

tensor([0.3387, 0.0061, 0.5150])

**Arange Array** - 1D array with evenly spaced values

In [18]:
np.arange(0, 5, 1)    # np.arange(start, stop, step) --- stop will not be included

array([0, 1, 2, 3, 4])

In [19]:
torch.arange(0, 5, 1)

tensor([0, 1, 2, 3, 4])

In [20]:
torch.arange(5)     # start and step parameters can be omitted

tensor([0, 1, 2, 3, 4])

**Slicing/Indexing** - take a part of data from original array by specifying indexes

In [21]:
a = np.arange(10) 
print(a)
print(a[2:5])    # take data from index 2 to before index 5

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [22]:
a = torch.arange(10)
print(a)
print(a[2:5])    # take data from index 2 to before index 5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 3, 4])


In [23]:
a = torch.arange(100).view(10,10)    # 10x10 torch.tensor
print(a)
print(a[1:3, 4:8])   # take 2D data from 10x10 torch.tensor

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
tensor([[14, 15, 16, 17],
        [24, 25, 26, 27]])


**Reshaping** 

In order to reshape the `numpy.ndarray`, we can use `.reshape()`.

In [24]:
a = np.arange(10) # 1D data
a.reshape(2,5)    # reshape data into 2x5 np.ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In PyTorch we need to use `.view()` instead of `.reshape()` for reshaping.

In [25]:
a = torch.arange(10)
a.view(2,5)   # reshape data into 2x5 torch.tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Argmax** - returns the index of element with the maximum value in given data

In [27]:
a = np.array([1, 2, 5, 3, 4])

print("a=", a)
print("argmax(a) =", np.argmax(a))    # Remember, the index number starts from 0 in Python

a= [1 2 5 3 4]
argmax(a) = 2


In [28]:
a = torch.tensor([1, 2, 5, 3, 4])

print("a=", a)
print("argmax(a) =", torch.argmax(a))

a= tensor([1, 2, 5, 3, 4])
argmax(a) = tensor(2)


**Practice**

Draw a graph of $y=\sin(x)$ by using PyTorch and Matplotlib, but not Numpy.

In [ ]:
# WRITE YOUR CODE HERE


## AutoGrad
One of the most important features of PyTorch is automatic differentiation engine `torch.autograd`. PyTorch performs calculations using computation graphs, and this allows us to access the gradients of outputs with respect to the inputs. This is the key for training neural networks.

Let's see a simple example of $y=2x+5$, where $x$ is input and $y$ is output.

In order to enable` torch.autograd` function, we need to set parameters of input `x` as `dtype=torch.float32`,  `requires_grad=True`.

In [29]:
x = torch.tensor(3.0, dtype=torch.float32, requires_grad=True)
y = 2*x + 5
print("y=", y)

y= tensor(11., grad_fn=<AddBackward0>)


By the way `y` is a torch.tensor data. You can take the value of `y` by `y.item()`.

In [30]:
y.item()

11.0

The gradients of `y` is calculated by `y.backward()`

In [31]:
y.backward()

Now the gradient of `y` respect to `x`, namely $dy/dx$, can be accessed by `x.grad`.

In [32]:
print("dy/dx =", x.grad)

dy/dx = tensor(2.)


**Practice**


1.   Define a new `torch.tensor` $x=5.0$
2.   Do calculation of $y=x^2 + 3x + 1$
3.   Determine the gradient of $dy/dx$ and check if that is correct.

In [ ]:
# WRITE YOUR CODE HERE


**Practice**


1.   Define a new `torch.tensor` $x=3.0$ and $y=2.0$
2.   Do calculation of $z=x^2 + 2y^3$
3.   Determine the partial gradients of $\partial z/\partial x$, $\partial z/\partial y$

In [ ]:
# WRITE YOUR CODE HERE


**Column**

In deep learning the gradient values are used for optimizing parameters of neural network models by a method so-called stochastic gradient descent (SGD) method. As we have seen above, PyTorch calculates the gradients of torch.tensors automatically. This is why PyTorch is used for deep learning programming.

If you are interested in how SGD works for optimizing parameters, here is an example.

https://colab.research.google.com/drive/1L4wrhEZojLRWqF8Dnui5qoyxwrcK29pf?usp=sharing
